version: '3.3'
services:

  api:
    image: api-image
    container_name: api
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - application

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - application

networks:
  application:
    driver: bridge
